include(common.pri)

CLIENTLIB_INCLUDEPATH= $${INC_PATH}/ClientLib
CLIENTLIB_LIBRARY = -lClientLib$${LIB_SUFFIX}

SSLCLIENTLIB_INCLUDEPATH= $${INC_PATH}/SSLClientLib
SSLCLIENTLIB_LIBRARY = -lSSLClientLib$${LIB_SUFFIX}
