CLIENTLIB_INCLUDEPATH= $${INC_PATH}/ClientLib
CLIENTLIB_LIBRARY = -lClientLib$${LIB_SUFFIX}

GUILIB_INCLUDEPATH= $${INC_PATH}/GuiLib
GUILIB_LIBRARY = -lGuiLib$${LIB_SUFFIX}

DBLIB_INCLUDEPATH= $${INC_PATH}/DBLib
DBLIB_LIBRARY = -lDBLib$${LIB_SUFFIX}

SERVERLIB_INCLUDEPATH= $${INC_PATH}/ServerLib
SERVERLIB_LIBRARY = -lServerLib$${LIB_SUFFIX}
