CLIENTLIB_INCLUDEPATH= $${INC_PATH}/ClientLib
CLIENTLIB_LIBRARY = -lClientLib$${LIB_SUFFIX}

GUILIB_INCLUDEPATH= $${INC_PATH}/GuiLib
GUILIB_LIBRARY = -lGuiLib$${LIB_SUFFIX}

SERVERLIB_INCLUDEPATH= $${INC_PATH}/ServerLib
SERVERLIB_LIBRARY = -lServerLib$${LIB_SUFFIX}

SSLCLIENTLIB_INCLUDEPATH= $${INC_PATH}/SSLClientLib
SSLCLIENTLIB_LIBRARY = -lSSLClientLib$${LIB_SUFFIX}

SSLSERVERLIB_INCLUDEPATH= $${INC_PATH}/SSLServerLib
SSLSERVERLIB_LIBRARY = -lSSLServerLib$${LIB_SUFFIX}
